---
- name: install ssmtp
  apt:
    name: ssmtp
    state: present

- name: configure ssmtp config
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    mode: 0640
    owner: root
    group: mail

- name: configure revaliases config
  template:
    src: revaliases.j2
    dest: /etc/ssmtp/revaliases
    mode: 0640
    owner: root
    group: mail
